const cartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  TOGGLE_CHECK: 'TOGGLE_CHECK',
  SAVE_LIST_NAME : 'SAVE_LIST_NAME',
  SAVE_LIST_START : 'SAVE_LIST_START',
  SAVE_LIST_SUCCESS : 'SAVE_LIST_SUCCESS',
  SAVE_LIST_ERROR : 'SAVE_LIST_ERROR',
  GET_LIST_START : 'GET_LIST_START',
  GET_LIST_SUCCESS : 'GET_LIST_SUCCESS',
  GET_LIST_ERROR : 'GET_LIST_ERROR'
}

export default cartActionTypes