const authActionTypes = {
    SIGN_UP_START : 'SIGN_UP_START',
    SIGN_UP_SUCCESS : 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR : 'SIGN_UP_ERROR',
    SIGN_UP_USER_EXIST : 'SIGN_UP_USER_EXIST',
    SIGN_IN_START : 'SIGN_IN_START',
    SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
    SIGN_IN_ERROR : 'SIGN_IN_ERROR',
    LOG_OUT : 'LOG_OUT',
    ERROR_RESET : 'ERROR_RESET'
}

export default authActionTypes