const itemActionTypes = {
  ADD_ITEM_START: 'ADD_ITEM_START',
  ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
  ADD_ITEM_ERROR: 'ADD_ITEM_ERROR',
  FETCH_ITEM_START: 'FETCH_ITEM_START',
  FETCH_ITEM_SUCCESS: 'FETCH_ITEM_SUCCESS',
  FETCH_ITEM_ERROR: 'FETCH_ITEM_ERROR',
  EDIT_ITEM_START: 'EDIT_ITEM_START',
  EDIT_ITEM_SUCCESS: 'EDIT_ITEM_SUCCESS',
  EDIT_ITEM_ERROR: 'EDIT_ITEM_ERROR'
}


export default itemActionTypes